#!/bin/sh
#
# DESCRIPTION
#
# Startup init script for BackupAFS on suse linux.
#
# Distributed with BackupAFS version 1.0.0, released 22 Nov 2010.
#

set -e

#
BINDIR=__INSTALLDIR__/bin
DATADIR=__TOPDIR__
LOGDIR=__LOGDIR__
USER=__BACKUPAFSUSER__
#
NAME=backupafs
DAEMON=BackupAFS

test -x $BINDIR/$DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting $NAME: "
    startproc -f  -p $LOGDIR/BackupAFS.pid -u $USER $BINDIR/$DAEMON -d 
    echo "ok."
    ;;
  stop)
    echo -n "Stopping $NAME: "
    start-stop-daemon --stop --pidfile $LOGDIR/BackupAFS.pid -u $USER \
			    --oknodo 
    echo "ok."
      ;;
  restart)
    echo -n "Stopping $NAME: "
    start-stop-daemon --stop --pidfile $LOGDIR/BackupAFS.pid -u $USER \
			    --oknodo 
    echo "ok."
    echo -n "Starting $NAME: "
    startproc -f  -p $LOGDIR/BackupAFS.pid -u $USER $BINDIR/$DAEMON -d 
    echo "ok."
    ;;
  reload|force-reload)
    echo "Reloading $NAME configuration files"
    start-stop-daemon --stop --pidfile $LOGDIR/BackupAFS.pid \
			    --signal 1 -x /usr/bin/perl
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload}"
    exit 1
    ;;
esac

exit 0
